const { test, expect } = require('./fixtures/test');

test.describe('Talent Application Workflow', () => {
  test('Talent can apply to a job using the 3-step wizard', async ({ page, loginPage, employerDashboard, talentDashboard }) => {

    // 1. Create a job as an Employer
    await loginPage.goto();
    await loginPage.loginAsEmployer();
    await employerDashboard.createJob('Automated Test Job', '100000', '150000');
    // Wait a brief moment to ensure job creation completes and UI is stable
    await page.waitForTimeout(1000);
    
    // Log out by clearing localStorage
    await page.evaluate(() => { localStorage.clear(); });

    // 2. Login as Talent to apply
    await loginPage.goto();
    await loginPage.loginAsTalent();

    await expect(talentDashboard.matchFeedTab).toHaveAttribute('data-state', 'active');
    await expect(page.getByRole('button', { name: 'Apply for this position' }).first()).toBeVisible({ timeout: 10000 });

    await talentDashboard.applyToFirstJob('This is an automated test cover letter generated by Playwright.');

    await talentDashboard.applicationHistoryTab.click();
    await expect(page.getByText('Manual', { exact: true }).first()).toBeVisible();
  });
});
